name: Unit testing

on:
  workflow_dispatch:

jobs:
  job1:
    name: unit_testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install pytest
    - name: Run unit tests
      run: | 
        pytest tests/
