name: Deploys the latest version of the registered model

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  endpoint:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Create endpoint
        run: bash -x az ml online-endpoint create --resource-group mslearn-dscp-resgroup --workspace-name mslearn-dscp-workspace --name mslearn-mlops-endpoint --file endpoint.yml
        working-directory: production
  deploy:
    environment: Production
    needs: endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy model to created endpoint
        run: bash -x az ml online-deployment create --resource-group mslearn-dscp-resgroup --workspace-name mslearn-dscp-workspace --name diabetes-prod --endpoint mslearn-mlops-endpoint --file deploy.yml --all-traffic
        working-directory: production
